### ISSUE TITLE
Error migrations

### ISSUE THREAD

**Issue by ghost** [borodulin/yii2-i18n-google#3]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

```  > create table {{%i18n_message}} ... done (time: 4.546s)
    > create table {{%i18n_translator}} ... done (time: 6.053s)
    > create table {{%i18n_translation}} ... done (time: 12.235s)
    > add foreign key fk_i18n_translation_message: {{%i18n_translation}} (message_id) references {{%i18n_message}} (message_id) ... done (time: 4.175s)
    > add foreign key fk_i18n_translation_translator: {{%i18n_translation}} (translator_id) references {{%i18n_translator}} (translator_id) ... done (time: 7.475s)
    > create index ix_i18n_translation_status on {{%i18n_translation}} (status) ... done (time: 2.337s)
    > create unique index ix_i18n_translator_class_name on {{%i18n_translator}} (class_name) ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
The SQL being executed was: ALTER TABLE `i18n_translator` ADD UNIQUE INDEX `ix_i18n_translator_class_name` (`class_name`) (/Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `i1...')
#1 /Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE `i1...')
#2 /Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/db/Migration.php(495): yii\db\Command->execute()
#3 /Users/aleksandr/web/ox/devex/vendor/conquer/i18n/migrations/m170610_152817_i18n.php(50): yii\db\Migration->createIndex('ix_i18n_transla...', '{{%i18n_transla...', 'class_name', true)
#4 /Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/db/Migration.php(114): m170610_152817_i18n->safeUp()
#5 /Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): yii\db\Migration->up()
#6 /Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(199): yii\console\controllers\BaseMigrateController->migrateUp('m170610_152817_...')
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#8 /Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#11 /Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#12 /Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate', Array)
#13 /Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate', Array)
#14 /Users/aleksandr/web/ox/devex/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#15 /Users/aleksandr/web/ox/devex/yii(23): yii\base\Application->run()
#16 {main}
*** failed to apply m170610_152817_i18n (time: 37.509s)


0 from 1 migrations were applied.

Migration failed. The rest of the migrations are canceled.
```

**Comment by ghost** [comment]
utf8mb4

**Comment by obmenltd** [comment]
Саша заебал ответь мне уже
